//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIAGNOSTICO()
        {
            this.PS_POS_CONDICIONADO = new HashSet<PS_POS_CONDICIONADO>();
        }
    
        public string DIAGNOSTICO1 { get; set; }
        public string DESCR_DIAGNOSTICO { get; set; }
        public string ABREVIAT { get; set; }
        public string SEXO { get; set; }
        public Nullable<short> EDAD_MINIMA { get; set; }
        public Nullable<short> EDAD_MAXIMA { get; set; }
        public string CAPITULO { get; set; }
        public string CATEGORIA { get; set; }
        public string SUBCATEGORIA { get; set; }
        public string IND_COBRO_COPAGO { get; set; }
        public string COD_ESPECIALIDAD { get; set; }
        public Nullable<short> COD_GRUPO_SP { get; set; }
        public string Aplica_Infrenal { get; set; }
        public string Cod_Sub_Grupo { get; set; }
    
        public virtual SEXO SEXO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PS_POS_CONDICIONADO> PS_POS_CONDICIONADO { get; set; }
    }
}
