//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GN_CONCEPTOS_CONTABLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GN_CONCEPTOS_CONTABLES()
        {
            this.PS_SERVICIOS = new HashSet<PS_SERVICIOS>();
        }
    
        public decimal CONCEPTO_CONTABLE { get; set; }
        public string DESC_CONCEPTO_CONTABLE { get; set; }
        public string TIPO_CONTRATO { get; set; }
        public string APLICA_RECOBROS { get; set; }
        public string APLICA_TUTELAS { get; set; }
        public string APLICA_PREDX_ESP { get; set; }
        public string COD_GRUPO_ACTIVIDAD { get; set; }
        public Nullable<int> COD_CCONTABLE_COORD { get; set; }
        public Nullable<int> COD_CCONTABLE_GERSALUD { get; set; }
        public Nullable<int> COD_CCONTABLE_NIVELAT { get; set; }
        public short PRIORIDAD { get; set; }
        public string CENTRO_COSTO { get; set; }
        public string CENTRO_COSTO_DET { get; set; }
        public string ESTADO_CONCEPTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PS_SERVICIOS> PS_SERVICIOS { get; set; }
    }
}
