//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GN_NIVEL_AUTORIZ
    {
        public int NIVEL_AUTORIZACION { get; set; }
        public string DESC_AUTORIZACION { get; set; }
        public string DESC_USUARIO { get; set; }
        public Nullable<bool> PYP_412 { get; set; }
    }
}
