//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GN_PLANES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GN_PLANES()
        {
            this.GN_ADMINXREGIONAL = new HashSet<GN_ADMINXREGIONAL>();
            this.PS_DETALLE_SERVICIOS = new HashSet<PS_DETALLE_SERVICIOS>();
        }
    
        public string COD_PLAN { get; set; }
        public string DESC_PLAN { get; set; }
        public string ABREVIAT { get; set; }
        public string RES_744_2012 { get; set; }
        public Nullable<int> COD_PLAN_NORMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GN_ADMINXREGIONAL> GN_ADMINXREGIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PS_DETALLE_SERVICIOS> PS_DETALLE_SERVICIOS { get; set; }
    }
}
