//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GN_TIPO_SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GN_TIPO_SERVICIOS()
        {
            this.GN_TIPO_TECNOLOGIA = new HashSet<GN_TIPO_TECNOLOGIA>();
            this.PS_SERVICIOS = new HashSet<PS_SERVICIOS>();
        }
    
        public short COD_TIPO_SERVICIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string EQU_CIRCULAR55 { get; set; }
        public string EQU_RECFOSYGA { get; set; }
        public string EQU_INTERFAZ { get; set; }
        public string RES_1683 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GN_TIPO_TECNOLOGIA> GN_TIPO_TECNOLOGIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PS_SERVICIOS> PS_SERVICIOS { get; set; }
    }
}
