//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPO()
        {
            this.SUB_GRUPO = new HashSet<SUB_GRUPO>();
        }
    
        public string COD_GRUPO { get; set; }
        public string DESCR_GRUPO { get; set; }
        public string ABRE_GRUPO { get; set; }
        public string MANUAL_TARIFARIO { get; set; }
        public Nullable<int> MOSTRARCONTRATACIONARCHIVOPLANO { get; set; }
        public Nullable<int> MOSTRARCONTRATACION { get; set; }
        public Nullable<bool> CARGUE_AUT_MASIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUB_GRUPO> SUB_GRUPO { get; set; }
    }
}
