//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_POS_CONDICIONADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PS_POS_CONDICIONADO()
        {
            this.PS_DETALLE_SERVICIOS = new HashSet<PS_DETALLE_SERVICIOS>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ID_PS_GRUPOS_ETAREOS { get; set; }
        public string DIAGNOSTICO { get; set; }
        public Nullable<long> CANTIDAD { get; set; }
        public string MENSAJE_INFORMATIVO { get; set; }
    
        public virtual DIAGNOSTICO DIAGNOSTICO1 { get; set; }
        public virtual PS_GRUPOS_ETAREOS PS_GRUPOS_ETAREOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PS_DETALLE_SERVICIOS> PS_DETALLE_SERVICIOS { get; set; }
    }
}
