//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruposEtareos.BI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PS_SERVICIOS()
        {
            this.PS_DETALLE_SERVICIOS = new HashSet<PS_DETALLE_SERVICIOS>();
        }
    
        public string COD_SERVICIO { get; set; }
        public string COD_GRUPO { get; set; }
        public string COD_SUBGRUPO { get; set; }
        public string DESCR_SERVICIO { get; set; }
        public string ABREVIATURA { get; set; }
        public string COD_ENTIDAD { get; set; }
        public string COD_CLASIF_CONTABLE { get; set; }
        public string APLICA_ESPECIALIDAD { get; set; }
        public decimal COD_CONCEPTOC_EVENTO { get; set; }
        public decimal COD_CONCEPTOC_CAPITA { get; set; }
        public string COD_ENTIDADSP { get; set; }
        public string COMPLEJIDAD { get; set; }
        public string REGISTRO_SANITARIO { get; set; }
        public Nullable<short> COD_TIPO_SERVICIO { get; set; }
        public Nullable<int> ID_ESTADO_SERVICIOS { get; set; }
        public string CUM { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<bool> FORMULA_MAGISTRAL { get; set; }
        public Nullable<bool> VITAL_DISPONIBLE { get; set; }
        public Nullable<long> ID_TECNOLOGIA { get; set; }
        public Nullable<bool> AUTORIZACION_RELACIONADA { get; set; }
        public string CODIGO_IUM { get; set; }
        public short NIVEL_AUTORIZACION { get; set; }
        public short EDAD_MINIMA { get; set; }
        public short EDAD_MAXIMA { get; set; }
        public string COD_SEXO { get; set; }
        public decimal UTILIZACION_MAXIMA { get; set; }
        public int PERIODO_UTILIZACION_MAXIMA { get; set; }
        public short PERIODO_TOPE_MAXIMO { get; set; }
        public short MAXIMOXORDEN { get; set; }
        public short DIAS_EXPIRACION { get; set; }
        public string AUTORIZACION_INICIAL { get; set; }
        public short DIAS_MAX_AUTORIZADOS { get; set; }
        public string VALOR_VARIABLE { get; set; }
        public string REVISION_DIAGNOSTICOS { get; set; }
        public string PROFESIONAL_AUTORIZA { get; set; }
        public Nullable<bool> APLICA_COPAGO { get; set; }
        public Nullable<bool> APLICA_CUOTAMODERADORA { get; set; }
        public Nullable<bool> EXCLUIRVALIDACION { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
    
        public virtual GN_CLASIFIC_CONTABLE GN_CLASIFIC_CONTABLE { get; set; }
        public virtual GN_CONCEPTOS_CONTABLES GN_CONCEPTOS_CONTABLES { get; set; }
        public virtual GN_TIPO_SERVICIOS GN_TIPO_SERVICIOS { get; set; }
        public virtual GN_TIPO_TECNOLOGIA GN_TIPO_TECNOLOGIA { get; set; }
        public virtual NIVEL_COMPLEJIDAD NIVEL_COMPLEJIDAD { get; set; }
        public virtual SEXO SEXO { get; set; }
        public virtual SUB_GRUPO SUB_GRUPO { get; set; }
        public virtual SV_ESTADO_SERVICIOS SV_ESTADO_SERVICIOS { get; set; }
        public virtual SV_PROFESIONAL_AUTORIZA SV_PROFESIONAL_AUTORIZA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PS_DETALLE_SERVICIOS> PS_DETALLE_SERVICIOS { get; set; }
    }
}
